name: Bug Report
description: Report a bug or unexpected behavior
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is
      placeholder: When I try to encode..., I expect..., but instead...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a Toon instance
        2. Call encode() with...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened (including error messages and stack traces)
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.1.15
        - 0.1.14
        - 0.1.13
        - 0.1.12
        - < 0.1.12
    validations:
      required: true

  - type: dropdown
    id: buildtool
    attributes:
      label: What building tool are you the problem on?
      multiple: true
      options:
          - Maven
          - Gradle

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide:
        - Java version
        - Operating system
      placeholder: |
        - Java 21.0.1
        - macOS 15.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (optional)
